[project]
name = "cloudlab-deployment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geni-lib>=0.9.9.4",
    "six>=1.17.0",
]
